/**
 * Generated Cloudflare API error classes.
 *
 * DO NOT EDIT - This file is generated by scripts/generate-errors.ts
 * To add new errors, update spec/error-catalog.json and regenerate.
 */

import * as Schema from "effect/Schema";

// =============================================================================
// AuthError
// =============================================================================

/**
 * Cloudflare error code 9000: Unauthorized
 */
export class Unauthorized extends Schema.TaggedError<Unauthorized>()("Unauthorized", {
  code: Schema.Literal(9000),
  message: Schema.String,
}) {
  static readonly code = 9000;
}

/**
 * Cloudflare error code 9103: InvalidToken
 */
export class InvalidToken extends Schema.TaggedError<InvalidToken>()("InvalidToken", {
  code: Schema.Literal(9103),
  message: Schema.String,
}) {
  static readonly code = 9103;
}

/**
 * Cloudflare error code 9106: MissingToken
 */
export class MissingToken extends Schema.TaggedError<MissingToken>()("MissingToken", {
  code: Schema.Literal(9106),
  message: Schema.String,
}) {
  static readonly code = 9106;
}

/**
 * Cloudflare error code 9109: TokenExpired
 */
export class TokenExpired extends Schema.TaggedError<TokenExpired>()("TokenExpired", {
  code: Schema.Literal(9109),
  message: Schema.String,
}) {
  static readonly code = 9109;
}

/**
 * Cloudflare error code 10000: AuthenticationError
 */
export class AuthenticationError extends Schema.TaggedError<AuthenticationError>()("AuthenticationError", {
  code: Schema.Literal(10000),
  message: Schema.String,
}) {
  static readonly code = 10000;
}

/**
 * Cloudflare error code 10002: Unauthorized
 */
export class Unauthorized_10002 extends Schema.TaggedError<Unauthorized_10002>()("Unauthorized_10002", {
  code: Schema.Literal(10002),
  message: Schema.String,
}) {
  static readonly code = 10002;
}

/**
 * Cloudflare error code 10003: AccessDenied
 */
export class AccessDenied extends Schema.TaggedError<AccessDenied>()("AccessDenied", {
  code: Schema.Literal(10003),
  message: Schema.String,
}) {
  static readonly code = 10003;
}

/**
 * Cloudflare error code 10015: NotEntitled
 */
export class NotEntitled extends Schema.TaggedError<NotEntitled>()("NotEntitled", {
  code: Schema.Literal(10015),
  message: Schema.String,
}) {
  static readonly code = 10015;
}

/**
 * Cloudflare error code 10018: ExpiredRequest
 */
export class ExpiredRequest extends Schema.TaggedError<ExpiredRequest>()("ExpiredRequest", {
  code: Schema.Literal(10018),
  message: Schema.String,
}) {
  static readonly code = 10018;
}

/**
 * Cloudflare error code 10042: NotEntitled
 */
export class NotEntitled_10042 extends Schema.TaggedError<NotEntitled_10042>()("NotEntitled_10042", {
  code: Schema.Literal(10042),
  message: Schema.String,
}) {
  static readonly code = 10042;
}

// =============================================================================
// BadRequestError
// =============================================================================

/**
 * Cloudflare error code 1000: InvalidRequest
 */
export class InvalidRequest extends Schema.TaggedError<InvalidRequest>()("InvalidRequest", {
  code: Schema.Literal(1000),
  message: Schema.String,
}) {
  static readonly code = 1000;
}

/**
 * Cloudflare error code 1001: InvalidFormat
 */
export class InvalidFormat extends Schema.TaggedError<InvalidFormat>()("InvalidFormat", {
  code: Schema.Literal(1001),
  message: Schema.String,
}) {
  static readonly code = 1001;
}

/**
 * Cloudflare error code 1002: InvalidType
 */
export class InvalidType extends Schema.TaggedError<InvalidType>()("InvalidType", {
  code: Schema.Literal(1002),
  message: Schema.String,
}) {
  static readonly code = 1002;
}

/**
 * Cloudflare error code 6003: InvalidMethod
 */
export class InvalidMethod extends Schema.TaggedError<InvalidMethod>()("InvalidMethod", {
  code: Schema.Literal(6003),
  message: Schema.String,
}) {
  static readonly code = 6003;
}

/**
 * Cloudflare error code 10005: InvalidBucketName
 */
export class InvalidBucketName extends Schema.TaggedError<InvalidBucketName>()("InvalidBucketName", {
  code: Schema.Literal(10005),
  message: Schema.String,
}) {
  static readonly code = 10005;
}

/**
 * Cloudflare error code 10010: ParseError
 */
export class ParseError extends Schema.TaggedError<ParseError>()("ParseError", {
  code: Schema.Literal(10010),
  message: Schema.String,
}) {
  static readonly code = 10010;
}

/**
 * Cloudflare error code 10011: EntityTooSmall
 */
export class EntityTooSmall extends Schema.TaggedError<EntityTooSmall>()("EntityTooSmall", {
  code: Schema.Literal(10011),
  message: Schema.String,
}) {
  static readonly code = 10011;
}

/**
 * Cloudflare error code 10012: MetadataTooLarge
 */
export class MetadataTooLarge extends Schema.TaggedError<MetadataTooLarge>()("MetadataTooLarge", {
  code: Schema.Literal(10012),
  message: Schema.String,
}) {
  static readonly code = 10012;
}

/**
 * Cloudflare error code 10013: IncompleteBody
 */
export class IncompleteBody extends Schema.TaggedError<IncompleteBody>()("IncompleteBody", {
  code: Schema.Literal(10013),
  message: Schema.String,
}) {
  static readonly code = 10013;
}

/**
 * Cloudflare error code 10014: InvalidDigest
 */
export class InvalidDigest extends Schema.TaggedError<InvalidDigest>()("InvalidDigest", {
  code: Schema.Literal(10014),
  message: Schema.String,
}) {
  static readonly code = 10014;
}

/**
 * Cloudflare error code 10016: InvalidWorkerName
 */
export class InvalidWorkerName extends Schema.TaggedError<InvalidWorkerName>()("InvalidWorkerName", {
  code: Schema.Literal(10016),
  message: Schema.String,
}) {
  static readonly code = 10016;
}

/**
 * Cloudflare error code 10019: NamespaceNameRequired
 */
export class NamespaceNameRequired extends Schema.TaggedError<NamespaceNameRequired>()("NamespaceNameRequired", {
  code: Schema.Literal(10019),
  message: Schema.String,
}) {
  static readonly code = 10019;
}

/**
 * Cloudflare error code 10020: InvalidObjectName
 */
export class InvalidObjectName extends Schema.TaggedError<InvalidObjectName>()("InvalidObjectName", {
  code: Schema.Literal(10020),
  message: Schema.String,
}) {
  static readonly code = 10020;
}

/**
 * Cloudflare error code 10021: ValidationError
 */
export class ValidationError extends Schema.TaggedError<ValidationError>()("ValidationError", {
  code: Schema.Literal(10021),
  message: Schema.String,
}) {
  static readonly code = 10021;
}

/**
 * Cloudflare error code 10025: InvalidPart
 */
export class InvalidPart extends Schema.TaggedError<InvalidPart>()("InvalidPart", {
  code: Schema.Literal(10025),
  message: Schema.String,
}) {
  static readonly code = 10025;
}

/**
 * Cloudflare error code 10026: InvalidRequestBody
 */
export class InvalidRequestBody extends Schema.TaggedError<InvalidRequestBody>()("InvalidRequestBody", {
  code: Schema.Literal(10026),
  message: Schema.String,
}) {
  static readonly code = 10026;
}

/**
 * Cloudflare error code 10027: WorkerSizeLimitExceeded
 */
export class WorkerSizeLimitExceeded extends Schema.TaggedError<WorkerSizeLimitExceeded>()("WorkerSizeLimitExceeded", {
  code: Schema.Literal(10027),
  message: Schema.String,
}) {
  static readonly code = 10027;
}

/**
 * Cloudflare error code 10033: MissingContentLength
 */
export class MissingContentLength extends Schema.TaggedError<MissingContentLength>()("MissingContentLength", {
  code: Schema.Literal(10033),
  message: Schema.String,
}) {
  static readonly code = 10033;
}

/**
 * Cloudflare error code 10037: BadDigest
 */
export class BadDigest extends Schema.TaggedError<BadDigest>()("BadDigest", {
  code: Schema.Literal(10037),
  message: Schema.String,
}) {
  static readonly code = 10037;
}

/**
 * Cloudflare error code 10039: InvalidRange
 */
export class InvalidRange extends Schema.TaggedError<InvalidRange>()("InvalidRange", {
  code: Schema.Literal(10039),
  message: Schema.String,
}) {
  static readonly code = 10039;
}

/**
 * Cloudflare error code 10040: BucketNameRequired
 */
export class BucketNameRequired extends Schema.TaggedError<BucketNameRequired>()("BucketNameRequired", {
  code: Schema.Literal(10040),
  message: Schema.String,
}) {
  static readonly code = 10040;
}

/**
 * Cloudflare error code 10048: InvalidPartSize
 */
export class InvalidPartSize extends Schema.TaggedError<InvalidPartSize>()("InvalidPartSize", {
  code: Schema.Literal(10048),
  message: Schema.String,
}) {
  static readonly code = 10048;
}

/**
 * Cloudflare error code 10052: BindingNameRequired
 */
export class BindingNameRequired extends Schema.TaggedError<BindingNameRequired>()("BindingNameRequired", {
  code: Schema.Literal(10052),
  message: Schema.String,
}) {
  static readonly code = 10052;
}

/**
 * Cloudflare error code 10054: EnvVarSizeExceeded
 */
export class EnvVarSizeExceeded extends Schema.TaggedError<EnvVarSizeExceeded>()("EnvVarSizeExceeded", {
  code: Schema.Literal(10054),
  message: Schema.String,
}) {
  static readonly code = 10054;
}

/**
 * Cloudflare error code 10055: EnvVarCountExceeded
 */
export class EnvVarCountExceeded extends Schema.TaggedError<EnvVarCountExceeded>()("EnvVarCountExceeded", {
  code: Schema.Literal(10055),
  message: Schema.String,
}) {
  static readonly code = 10055;
}

/**
 * Cloudflare error code 10068: NoEventHandlers
 */
export class NoEventHandlers extends Schema.TaggedError<NoEventHandlers>()("NoEventHandlers", {
  code: Schema.Literal(10068),
  message: Schema.String,
}) {
  static readonly code = 10068;
}

/**
 * Cloudflare error code 10069: UnsupportedEventHandlers
 */
export class UnsupportedEventHandlers extends Schema.TaggedError<UnsupportedEventHandlers>()("UnsupportedEventHandlers", {
  code: Schema.Literal(10069),
  message: Schema.String,
}) {
  static readonly code = 10069;
}

/**
 * Cloudflare error code 11003: InvalidQueueName
 */
export class InvalidQueueName extends Schema.TaggedError<InvalidQueueName>()("InvalidQueueName", {
  code: Schema.Literal(11003),
  message: Schema.String,
}) {
  static readonly code = 11003;
}

/**
 * Cloudflare error code 100100: EntityTooLarge
 */
export class EntityTooLarge extends Schema.TaggedError<EntityTooLarge>()("EntityTooLarge", {
  code: Schema.Literal(100100),
  message: Schema.String,
}) {
  static readonly code = 100100;
}

// =============================================================================
// NotFoundError
// =============================================================================

/**
 * Cloudflare error code 1003: InvalidZone
 */
export class InvalidZone extends Schema.TaggedError<InvalidZone>()("InvalidZone", {
  code: Schema.Literal(1003),
  message: Schema.String,
}) {
  static readonly code = 1003;
}

/**
 * Cloudflare error code 1004: RecordNotFound
 */
export class RecordNotFound extends Schema.TaggedError<RecordNotFound>()("RecordNotFound", {
  code: Schema.Literal(1004),
  message: Schema.String,
}) {
  static readonly code = 1004;
}

/**
 * Cloudflare error code 7000: NoRouteForURI
 */
export class NoRouteForURI extends Schema.TaggedError<NoRouteForURI>()("NoRouteForURI", {
  code: Schema.Literal(7000),
  message: Schema.String,
}) {
  static readonly code = 7000;
}

/**
 * Cloudflare error code 7003: NoRoute
 */
export class NoRoute extends Schema.TaggedError<NoRoute>()("NoRoute", {
  code: Schema.Literal(7003),
  message: Schema.String,
}) {
  static readonly code = 7003;
}

/**
 * Cloudflare error code 10006: NoSuchBucket
 */
export class NoSuchBucket extends Schema.TaggedError<NoSuchBucket>()("NoSuchBucket", {
  code: Schema.Literal(10006),
  message: Schema.String,
}) {
  static readonly code = 10006;
}

/**
 * Cloudflare error code 10007: NoSuchKey
 */
export class NoSuchKey extends Schema.TaggedError<NoSuchKey>()("NoSuchKey", {
  code: Schema.Literal(10007),
  message: Schema.String,
}) {
  static readonly code = 10007;
}

/**
 * Cloudflare error code 10024: NoSuchUpload
 */
export class NoSuchUpload extends Schema.TaggedError<NoSuchUpload>()("NoSuchUpload", {
  code: Schema.Literal(10024),
  message: Schema.String,
}) {
  static readonly code = 10024;
}

/**
 * Cloudflare error code 10056: BindingNotFound
 */
export class BindingNotFound extends Schema.TaggedError<BindingNotFound>()("BindingNotFound", {
  code: Schema.Literal(10056),
  message: Schema.String,
}) {
  static readonly code = 10056;
}

/**
 * Cloudflare error code 10059: NoCorsConfiguration
 */
export class NoCorsConfiguration extends Schema.TaggedError<NoCorsConfiguration>()("NoCorsConfiguration", {
  code: Schema.Literal(10059),
  message: Schema.String,
}) {
  static readonly code = 10059;
}

/**
 * Cloudflare error code 11000: QueueNotFound
 */
export class QueueNotFound extends Schema.TaggedError<QueueNotFound>()("QueueNotFound", {
  code: Schema.Literal(11000),
  message: Schema.String,
}) {
  static readonly code = 11000;
}

// =============================================================================
// ConflictError
// =============================================================================

/**
 * Cloudflare error code 10008: BucketNotEmpty
 */
export class BucketNotEmpty extends Schema.TaggedError<BucketNotEmpty>()("BucketNotEmpty", {
  code: Schema.Literal(10008),
  message: Schema.String,
}) {
  static readonly code = 10008;
}

/**
 * Cloudflare error code 10031: PreconditionFailed
 */
export class PreconditionFailed extends Schema.TaggedError<PreconditionFailed>()("PreconditionFailed", {
  code: Schema.Literal(10031),
  message: Schema.String,
}) {
  static readonly code = 10031;
}

/**
 * Cloudflare error code 10035: ConcurrentModification
 */
export class ConcurrentModification extends Schema.TaggedError<ConcurrentModification>()("ConcurrentModification", {
  code: Schema.Literal(10035),
  message: Schema.String,
}) {
  static readonly code = 10035;
}

/**
 * Cloudflare error code 10073: BucketConflict
 */
export class BucketConflict extends Schema.TaggedError<BucketConflict>()("BucketConflict", {
  code: Schema.Literal(10073),
  message: Schema.String,
}) {
  static readonly code = 10073;
}

/**
 * Cloudflare error code 11009: QueueAlreadyExists
 */
export class QueueAlreadyExists extends Schema.TaggedError<QueueAlreadyExists>()("QueueAlreadyExists", {
  code: Schema.Literal(11009),
  message: Schema.String,
}) {
  static readonly code = 11009;
}

// =============================================================================
// ThrottlingError
// =============================================================================

/**
 * Cloudflare error code 971: RateLimited
 */
export class RateLimited extends Schema.TaggedError<RateLimited>()("RateLimited", {
  code: Schema.Literal(971),
  message: Schema.String,
}) {
  static readonly code = 971;
}

/**
 * Cloudflare error code 6100: TooManyRequests
 */
export class TooManyRequests extends Schema.TaggedError<TooManyRequests>()("TooManyRequests", {
  code: Schema.Literal(6100),
  message: Schema.String,
}) {
  static readonly code = 6100;
}

/**
 * Cloudflare error code 10009: TooManyBuckets
 */
export class TooManyBuckets extends Schema.TaggedError<TooManyBuckets>()("TooManyBuckets", {
  code: Schema.Literal(10009),
  message: Schema.String,
}) {
  static readonly code = 10009;
}

/**
 * Cloudflare error code 10058: TooManyRequests
 */
export class TooManyRequests_10058 extends Schema.TaggedError<TooManyRequests_10058>()("TooManyRequests_10058", {
  code: Schema.Literal(10058),
  message: Schema.String,
}) {
  static readonly code = 10058;
}

// =============================================================================
// ServerError
// =============================================================================

/**
 * Cloudflare error code 10001: InternalError
 */
export class InternalError extends Schema.TaggedError<InternalError>()("InternalError", {
  code: Schema.Literal(10001),
  message: Schema.String,
}) {
  static readonly code = 10001;
}

/**
 * Cloudflare error code 10043: ServiceUnavailable
 */
export class ServiceUnavailable extends Schema.TaggedError<ServiceUnavailable>()("ServiceUnavailable", {
  code: Schema.Literal(10043),
  message: Schema.String,
}) {
  static readonly code = 10043;
}

// =============================================================================
// Union Types
// =============================================================================

export type AuthErrors = Unauthorized | InvalidToken | MissingToken | TokenExpired | AuthenticationError | Unauthorized_10002 | AccessDenied | NotEntitled | ExpiredRequest | NotEntitled_10042;
export type BadRequestErrors = InvalidRequest | InvalidFormat | InvalidType | InvalidMethod | InvalidBucketName | ParseError | EntityTooSmall | MetadataTooLarge | IncompleteBody | InvalidDigest | InvalidWorkerName | NamespaceNameRequired | InvalidObjectName | ValidationError | InvalidPart | InvalidRequestBody | WorkerSizeLimitExceeded | MissingContentLength | BadDigest | InvalidRange | BucketNameRequired | InvalidPartSize | BindingNameRequired | EnvVarSizeExceeded | EnvVarCountExceeded | NoEventHandlers | UnsupportedEventHandlers | InvalidQueueName | EntityTooLarge;
export type NotFoundErrors = InvalidZone | RecordNotFound | NoRouteForURI | NoRoute | NoSuchBucket | NoSuchKey | NoSuchUpload | BindingNotFound | NoCorsConfiguration | QueueNotFound;
export type ConflictErrors = BucketNotEmpty | PreconditionFailed | ConcurrentModification | BucketConflict | QueueAlreadyExists;
export type ThrottlingErrors = RateLimited | TooManyRequests | TooManyBuckets | TooManyRequests_10058;
export type ServerErrors = InternalError | ServiceUnavailable;

export type CloudflareKnownError = Unauthorized | InvalidToken | MissingToken | TokenExpired | AuthenticationError | Unauthorized_10002 | AccessDenied | NotEntitled | ExpiredRequest | NotEntitled_10042 | InvalidRequest | InvalidFormat | InvalidType | InvalidMethod | InvalidBucketName | ParseError | EntityTooSmall | MetadataTooLarge | IncompleteBody | InvalidDigest | InvalidWorkerName | NamespaceNameRequired | InvalidObjectName | ValidationError | InvalidPart | InvalidRequestBody | WorkerSizeLimitExceeded | MissingContentLength | BadDigest | InvalidRange | BucketNameRequired | InvalidPartSize | BindingNameRequired | EnvVarSizeExceeded | EnvVarCountExceeded | NoEventHandlers | UnsupportedEventHandlers | InvalidQueueName | EntityTooLarge | InvalidZone | RecordNotFound | NoRouteForURI | NoRoute | NoSuchBucket | NoSuchKey | NoSuchUpload | BindingNotFound | NoCorsConfiguration | QueueNotFound | BucketNotEmpty | PreconditionFailed | ConcurrentModification | BucketConflict | QueueAlreadyExists | RateLimited | TooManyRequests | TooManyBuckets | TooManyRequests_10058 | InternalError | ServiceUnavailable;

/**
 * Map of error codes to their error class constructors.
 */
export const ERROR_CODE_MAP = {
  9000: Unauthorized,
  9103: InvalidToken,
  9106: MissingToken,
  9109: TokenExpired,
  10000: AuthenticationError,
  10002: Unauthorized_10002,
  10003: AccessDenied,
  10015: NotEntitled,
  10018: ExpiredRequest,
  10042: NotEntitled_10042,
  1000: InvalidRequest,
  1001: InvalidFormat,
  1002: InvalidType,
  6003: InvalidMethod,
  10005: InvalidBucketName,
  10010: ParseError,
  10011: EntityTooSmall,
  10012: MetadataTooLarge,
  10013: IncompleteBody,
  10014: InvalidDigest,
  10016: InvalidWorkerName,
  10019: NamespaceNameRequired,
  10020: InvalidObjectName,
  10021: ValidationError,
  10025: InvalidPart,
  10026: InvalidRequestBody,
  10027: WorkerSizeLimitExceeded,
  10033: MissingContentLength,
  10037: BadDigest,
  10039: InvalidRange,
  10040: BucketNameRequired,
  10048: InvalidPartSize,
  10052: BindingNameRequired,
  10054: EnvVarSizeExceeded,
  10055: EnvVarCountExceeded,
  10068: NoEventHandlers,
  10069: UnsupportedEventHandlers,
  11003: InvalidQueueName,
  100100: EntityTooLarge,
  1003: InvalidZone,
  1004: RecordNotFound,
  7000: NoRouteForURI,
  7003: NoRoute,
  10006: NoSuchBucket,
  10007: NoSuchKey,
  10024: NoSuchUpload,
  10056: BindingNotFound,
  10059: NoCorsConfiguration,
  11000: QueueNotFound,
  10008: BucketNotEmpty,
  10031: PreconditionFailed,
  10035: ConcurrentModification,
  10073: BucketConflict,
  11009: QueueAlreadyExists,
  971: RateLimited,
  6100: TooManyRequests,
  10009: TooManyBuckets,
  10058: TooManyRequests_10058,
  10001: InternalError,
  10043: ServiceUnavailable,
} as const;

export type ErrorCodeMap = typeof ERROR_CODE_MAP;

/**
 * Error catalog for response parser.
 * Maps error codes to their names (matching the class identifiers).
 */
export const ERROR_CATALOG: Map<number, { name: string; category: string }> = new Map([
  [971, { name: "RateLimited", category: "ThrottlingError" }],
  [1000, { name: "InvalidRequest", category: "BadRequestError" }],
  [1001, { name: "InvalidFormat", category: "BadRequestError" }],
  [1002, { name: "InvalidType", category: "BadRequestError" }],
  [1003, { name: "InvalidZone", category: "NotFoundError" }],
  [1004, { name: "RecordNotFound", category: "NotFoundError" }],
  [6003, { name: "InvalidMethod", category: "BadRequestError" }],
  [6100, { name: "TooManyRequests", category: "ThrottlingError" }],
  [7000, { name: "NoRouteForURI", category: "NotFoundError" }],
  [7003, { name: "NoRoute", category: "NotFoundError" }],
  [9000, { name: "Unauthorized", category: "AuthError" }],
  [9103, { name: "InvalidToken", category: "AuthError" }],
  [9106, { name: "MissingToken", category: "AuthError" }],
  [9109, { name: "TokenExpired", category: "AuthError" }],
  [10000, { name: "AuthenticationError", category: "AuthError" }],
  [10001, { name: "InternalError", category: "ServerError" }],
  [10002, { name: "Unauthorized_10002", category: "AuthError" }],
  [10003, { name: "AccessDenied", category: "AuthError" }],
  [10005, { name: "InvalidBucketName", category: "BadRequestError" }],
  [10006, { name: "NoSuchBucket", category: "NotFoundError" }],
  [10007, { name: "NoSuchKey", category: "NotFoundError" }],
  [10008, { name: "BucketNotEmpty", category: "ConflictError" }],
  [10009, { name: "TooManyBuckets", category: "ThrottlingError" }],
  [10010, { name: "ParseError", category: "BadRequestError" }],
  [10011, { name: "EntityTooSmall", category: "BadRequestError" }],
  [10012, { name: "MetadataTooLarge", category: "BadRequestError" }],
  [10013, { name: "IncompleteBody", category: "BadRequestError" }],
  [10014, { name: "InvalidDigest", category: "BadRequestError" }],
  [10015, { name: "NotEntitled", category: "AuthError" }],
  [10016, { name: "InvalidWorkerName", category: "BadRequestError" }],
  [10018, { name: "ExpiredRequest", category: "AuthError" }],
  [10019, { name: "NamespaceNameRequired", category: "BadRequestError" }],
  [10020, { name: "InvalidObjectName", category: "BadRequestError" }],
  [10021, { name: "ValidationError", category: "BadRequestError" }],
  [10024, { name: "NoSuchUpload", category: "NotFoundError" }],
  [10025, { name: "InvalidPart", category: "BadRequestError" }],
  [10026, { name: "InvalidRequestBody", category: "BadRequestError" }],
  [10027, { name: "WorkerSizeLimitExceeded", category: "BadRequestError" }],
  [10031, { name: "PreconditionFailed", category: "ConflictError" }],
  [10033, { name: "MissingContentLength", category: "BadRequestError" }],
  [10035, { name: "ConcurrentModification", category: "ConflictError" }],
  [10037, { name: "BadDigest", category: "BadRequestError" }],
  [10039, { name: "InvalidRange", category: "BadRequestError" }],
  [10040, { name: "BucketNameRequired", category: "BadRequestError" }],
  [10042, { name: "NotEntitled_10042", category: "AuthError" }],
  [10043, { name: "ServiceUnavailable", category: "ServerError" }],
  [10048, { name: "InvalidPartSize", category: "BadRequestError" }],
  [10052, { name: "BindingNameRequired", category: "BadRequestError" }],
  [10054, { name: "EnvVarSizeExceeded", category: "BadRequestError" }],
  [10055, { name: "EnvVarCountExceeded", category: "BadRequestError" }],
  [10056, { name: "BindingNotFound", category: "NotFoundError" }],
  [10058, { name: "TooManyRequests_10058", category: "ThrottlingError" }],
  [10059, { name: "NoCorsConfiguration", category: "NotFoundError" }],
  [10068, { name: "NoEventHandlers", category: "BadRequestError" }],
  [10069, { name: "UnsupportedEventHandlers", category: "BadRequestError" }],
  [10073, { name: "BucketConflict", category: "ConflictError" }],
  [11000, { name: "QueueNotFound", category: "NotFoundError" }],
  [11003, { name: "InvalidQueueName", category: "BadRequestError" }],
  [11009, { name: "QueueAlreadyExists", category: "ConflictError" }],
  [100100, { name: "EntityTooLarge", category: "BadRequestError" }],
]);
